# Generated by Django 3.2.8 on 2021-12-02 09:33

import account.models
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=155)),
                ('last_name', models.CharField(max_length=155)),
                ('group', models.CharField(choices=[('AIN-1-21', 'AIN-1-21'), ('AIN-2-21', 'AIN-2-21'), ('AIN-3-21', 'AIN-3-21'), ('WIN-1-21', 'WIN-1-21'), ('MIN-1-21', 'MIN-1-21'), ('AIN-1-20', 'AIN-1-20'), ('AIN-2-20', 'AIN-2-20'), ('AIN-3-20', 'AIN-3-20'), ('WIN-1-20', 'WIN-1-20'), ('MIN-1-20', 'MIN-1-20'), ('AIN-1-19', 'AIN-1-19'), ('AIN-2-19', 'AIN-2-19'), ('AIN-3-19', 'AIN-3-19'), ('WIN-1-19', 'WIN-1-19'), ('MIN-1-19', 'MIN-1-19'), ('AIN-1-18', 'AIN-1-18'), ('AIN-2-18', 'AIN-2-18'), ('AIN-3-18', 'AIN-3-18'), ('WIN-1-18', 'WIN-1-18'), ('MIN-1-18', 'MIN-1-18'), ('admin', 'admin')], max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_active', models.BooleanField(default=False)),
                ('activation_code', models.CharField(blank=True, max_length=20)),
                ('s_password', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', account.models.MyUserManager()),
            ],
        ),
    ]
