# Generated by Django 3.2.8 on 2021-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='s_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
