# Generated by Django 3.2.8 on 2021-10-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='group',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
